version: '3'
services:
  strapi:
    container_name: nzse_strapi
    image: mystrapi:latest
    build:
      context: ./cms
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    platform: linux/amd64
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./cms/src:/opt/app/src
      - ./cms/package.json:/opt/app/package.json
      - ./cms/yarn.lock:/opt/app/yarn.lock
      - ./.env:/opt/app/.env
      - /opt/app/node_modules
    ports:
      - ${STRAPI_PORT}:1337
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks: 
      - strapi-app-network

  client:
    container_name: nzse_client
    env_file: .env
    build:
      context: ./client
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - ${CLIENT_PORT}:3000
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    depends_on:
      - strapi
    command: sh -c './docker-scripts/wait-for.sh strapi:${STRAPI_PORT} -t 0 -- yarn dev'
    networks: 
      - strapi-app-network

  postgres:
    image: postgres
    env_file: .env
    restart: unless-stopped
    container_name: nzse_postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    
  pgadmin:
    container_name: nzse_pgadmin
    depends_on:
        - postgres
    image: dpage/pgadmin4
    restart: always
    ports: 
        - ${DATABASE_ADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DATABASE_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
    networks: 
      - strapi-app-network

networks:
  strapi-app-network:
    driver: bridge
