name: Deploy CMS to Digital Ocean
on:
  push:
    branches:
      - "deploy-production"

jobs:
  lint-client:
    uses: ./.github/workflows/lint-client.workflow.yml
  deploy-cms:
    runs-on: ubuntu-18.04
    steps:
      - uses: digitalocean/app_action@main
        with:
          app_name: nzse-admin
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
