name: Lint Client

on:
  push:
    branches:
      - main
      - deploy-production
  pull_request:
    branches:
      - main
      - deploy-production    

jobs:
  lint-client:
    name: Run ESLint
    runs-on: ubuntu-18.04
    steps:
      - name: Check out github repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        working-directory: ./client
        run: yarn install --frozen-lockfile
      
      - name: Run lint
        working-directory: ./client
        run: yarn lint
